# case_name = ["args", option<grade>]
# Functionality: 55
args-none = ["", 2]
args-many = ["a b c d e f g h i j k l m n o p q r s t u v", 2]
open-create = ["", 2]
open-rdwr = ["", 2]
open-trunc = ["", 2]
open-many = ["", 2]
read-zero = ["", 2]
read-normal = ["", 2]
write-zero = ["", 2]
write-normal = ["", 2]
close-normal = ["", 2]
exec-once = ["", 2]
exec-multiple = ["", 2]
exec-arg = ["", 2]
wait-simple = ["", 2]
wait-twice = ["", 2]
exit = ["", 2]
halt = ["", 2]
rox-simple = ["", 2]
rox-child = ["", 2]
rox-multichild = ["", 2]
multi-recurse = ["15", 13]
# Robustness: 45
close-stdio = ["", 2]
close-badfd = ["", 2]
close-twice = ["", 2]
read-badfd = ["", 2]
read-stdout = ["", 2]
write-badfd = ["", 2]
write-stdin = ["", 2]
boundary-normal = ["", 2]
boundary-bad = ["", 2]
open-invalid = ["", 2]
sc-bad-sp = ["", 2]
exec-invalid = ["", 2]
wait-badpid = ["", 2]
wait-killed = ["", 2]
bad-load = ["", 2]
bad-store = ["", 2]
bad-jump = ["", 2]
bad-load2 = ["", 2]
bad-store2 = ["", 2]
bad-jump2 = ["", 2]
sc-bad-args = ["", 5]
