# case_name = ["args", option<grade>]
# MMAP: 24
mmap-clean = ["", 3]
mmap-close = ["", 3]
mmap-read = ["", 3]
mmap-remove = ["", 3]
mmap-twice = ["", 3]
mmap-unmap = ["", 3]
mmap-write = ["", 3]
mmap-shuffle = ["", 3]
# Paging: 30
page-linear = ["", 9, 600]
page-parallel = ["", 3, 600]
page-merge-mm = ["", 3, 600]
page-merge-par = ["", 3, 600]
page-merge-seq = ["", 9, 600]
page-merge-stk = ["", 3, 600]
# Robustness: 46
pt-bad-addr = ["", 2]
pt-bad-read = ["", 2]
pt-write-code = ["", 2]
pt-write-code2 = ["", 2]
pt-big-stk-obj = ["", 3]
pt-grow-bad = ["", 3]
pt-grow-stack = ["", 3]
pt-grow-stk-sc = ["", 3]
mmap-bad-fd = ["", 2]
mmap-inherit = ["", 3]
mmap-null = ["", 3]
mmap-zero = ["", 3]
mmap-misalign = ["", 3]
mmap-over-code = ["", 3]
mmap-over-data = ["", 3]
mmap-over-stk = ["", 3]
mmap-overlap = ["", 3]
