# case_name = ["args", option<grade>]
sync = [""]
sync-condvar = [""]
sync-sema_fifo = [""]
thread-adder = [""]
thread-block = [""]
thread-bomb = [""]
thread-spin_yield = [""]
thread-spin_interrupt = [""]
mem-malloc = [""]
fs-inmem = [""]
fs-disk = [""]
fs-disk-simple = [""]
virtio = [""]
virtio-simple = [""]
